export const SWORD_TYPES = [
    "Arming Sword",
    "Zweihänder",
    "Claymore (Two-handed Highland)",
    "Claymore (Basket-hilted)",
    "Longsword",
    "Basket-hilted Sword",
    "Schiavona",
    "Mortuary Sword",
    "Scottish Broadsword",
    "Sinclair Hilt Sword",
    "Walloon Sword",
    "Falchion",
    "Flame-bladed Sword (Flambard/Flammard)",
    "Flamberge (Rapier style)",
    "Sabre",
    "Mameluke Sword",
    "Katana",
    "Ulfberht",
    "Broadsword",
    "Bastard Sword (Hand-and-a-half)",
    "Great Sword",
    "Side-sword",
    "Rapier",
    "Small-sword",
    "Kopis",
    "Cutlass",
    "Scimitar",
    "Xiphos",
    "Gladius"
];
