// Fix: Created the TermsPage component.
import React from 'react';

const TermsPage: React.FC = () => {
    return (
        <main className="container mx-auto px-4 py-16">
            <div className="w-full max-w-3xl mx-auto">
                 <h1 className="font-cinzel text-5xl font-bold text-teal-200 text-glow mb-8 text-center">
                    Terms of Service
                </h1>
                <div className="bg-gray-900/50 p-8 rounded-xl border border-teal-500/20 glow-border space-y-4 text-lg text-gray-300">
                    <p>By using this application, you agree to the following terms:</p>
                    <p>1. This is a technology demonstration and is provided "as-is" without warranty of any kind.</p>
                    <p>2. The content is generated by an AI model. It may sometimes be inaccurate, repetitive, or nonsensical. You are responsible for any use of the generated content.</p>
                    <p>3. Do not enter any sensitive or personal information into the generation forms.</p>
                    <p>4. You retain ownership of the prompts you provide and the generated content, subject to the terms of the underlying AI model provider (Google Gemini API).</p>
                </div>
            </div>
        </main>
    );
};

export default TermsPage;
